swagger: '2.0'
info:
  title: 'Discourse API'
  description: 'Move your app forward with the Discourse API'
  version: 1.0.0
host: discourse.example.com
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /categories.json:
    get:
      summary: Get a list of categories
      description: |
        The Categories endpoint returns a list of all the categories for
        your discourse site that you have access to.
      parameters: []
      tags:
        - Categories
      responses:
        '200':
          description: A category_list object that contains an array of categories
          schema:
            $ref: 'definitions/categories/categories.yml'
    post:
      description: Creats a new category
      parameters:
        - name: name
          in: body
          description:
          required: true
          schema:
            $ref: 'definitions/categories/new_category.yml'
      tags:
        - Categories
      responses:
        '200':
          description: category response
          schema:
            $ref: 'definitions/categories/new_category_response.yml'
  /c/{id}.json:
    get:
      description: |
        Get a single category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: category response
          schema:
            $ref: 'definitions/categories/category_response.yml'
  /posts:
    post:
      description: |
        Creates a new topic
      tags:
        - Topics
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: 'definitions/topics/new_topic.yml'
      responses:
        '200':
          description: new topic response
          schema:
            $ref: 'definitions/topics/new_topic_response.yml'
