swagger: '2.0'
info:
  title: 'Discourse API'
  description: 'Move your app forward with the Discourse API'
  version: 1.0.0
host: discourse.example.com
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /categories.json:
    get:
      summary: Get a list of categories
      description: |
        The Categories endpoint returns a list of all the categories for
        your discourse site that you have access to.
      parameters: []
      tags:
        - Categories
      responses:
        '200':
          description: |
            A category_list object that contains an array of categories
          schema:
            $ref: 'definitions/categories/categories.yml'
    post:
      description: Create a new category
      parameters:
        - name: name
          in: body
          required: true
          schema:
            $ref: 'definitions/categories/new_category.yml'
      tags:
        - Categories
      responses:
        '200':
          description: category response
          schema:
            $ref: 'definitions/categories/new_category_response.yml'
  /c/{id}.json:
    get:
      description: |
        Get a single category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: category response
          schema:
            $ref: 'definitions/categories/category_response.yml'
  /categories/{id}:
    put:
      description: |
        Update a single category
      tags:
        - Categories
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: 'definitions/categories/update_category.yml'
      responses:
        '200':
          description: update category response
          schema:
            $ref: 'definitions/categories/update_category_response.yml'
  /posts:
    post:
      description: |
        Create a new topic or a new post on an existing topic.
      tags:
        - Topics
        - Posts
      parameters:
        - name: body
          in: body
          required: false
          schema:
            type: object
            required:
              - raw
            properties:
              title:
                type: string
                description: required if creating a new topic
              topic_id:
                type: integer
                description: required if creating a new post
              raw:
                type: string
      responses:
        '200':
          description: new topic response
          schema:
            $ref: 'definitions/topics/new_topic_response.yml'
  /posts/{id}:
    get:
      description: |
        Get a single post
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: post response
          schema:
            $ref: 'definitions/posts/get_post_response.yml'
    put:
      description: |
        Update a single post
      tags:
        - Posts
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: body
          in: body
          schema:
            type: object
            properties:
              post[raw]:
                type: string
      responses:
        '200':
          description: update post response
          schema:
            $ref: 'definitions/posts/update_post_response.yml'
  /t/{id}.json:
    get:
      description: |
        Get a single topic
      tags:
        - Topics
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: topic response
          schema:
            $ref: 'definitions/topics/topic_response.yml'
    delete:
      description: |
        Remove a single topic
      tags:
        - Topics
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: |
            delete topic response is empty, just a status code
  /t/{slug}/{id}.json:
    put:
      description: |
        Update a single topic
      tags:
        - Topics
      parameters:
        - name: slug
          in: path
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: integer
        - name: body
          in: body
          required: true
          schema:
            $ref: 'definitions/topics/update_topic.yml'
      responses:
        '200':
          description: update topic response
          schema:
            $ref: 'definitions/topics/update_topic_response.yml'
